name: QPLANT Build & Export

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Run recursive builder
        run: python recursive_builder.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qplant-outputs
          path: outputs/**
